# Generated by Django 4.2.4 on 2023-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatedirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no_primary', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('contact_no_alternate', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Candidatedirectory',
            },
        ),
    ]
